### ISSUE TITLE
Error: local-exec provisioner error : exit status 127. Output: /bin/sh: 1: virtualenv: not found │ /bin/sh: 2: ansible-playbook: not found

### ISSUE THREAD

**Issue by LoesterFranco** [MusicDin/terraform-kvm-kubespray#13]
│ Error: local-exec provisioner error
│ 
│   with module.k8s_cluster.null_resource.haproxy_install[0],
│   on modules/cluster/k8s-cluster.tf line 311, in resource "null_resource" "haproxy_install":
│  311:   provisioner "local-exec" {
│ 
│ Error running command 'virtualenv -p python3 venv && . venv/bin/activate && pip3 install -r
│ requirements.txt
│ ansible-playbook \
│   --inventory config/hosts.ini \
│   --become \
│   --user=$SSH_USER \
│   --private-key=$SSH_PRIVATE_KEY \
│   $EXTRA_ARGS \
│   ansible/haproxy/haproxy.yml
│ ': exit status 127. Output: /bin/sh: 1: virtualenv: not found
│ /bin/sh: 2: ansible-playbook: not found

**Comment by MusicDin** [comment]
You need to have [virtualenv](https://virtualenv.pypa.io/en/latest/) installed. 
This way a separate Python environment will be created and all dependencies related to this project will be installed in it, keeping your global environment/dependencies intact.

You can install virtualenv with `apt` if you are running Ubuntu, or with Python `pip`. See [how to install virtualenv](https://virtualenv.pypa.io/en/latest/installation.html).

Please let me know if this solves your problem.

**Comment by LoesterFranco** [comment]
sudo apt-get install -y python3 python3-dev python3-pip python3-venv python3-virtualenv ansible
pip3 install virtualenv
pip3 install ansible

**Comment by MusicDin** [comment]
Thank you for your feedback.

Just to clarify, installing `python3` and `python3-virtualenv` should be sufficient as Ansible will be installed later in the created virtual environment along with other project dependencies.
